// const a = {
//     "nombre": "EMPRESAUNO",
//     "responsable": "jefe 1",
//     "correo": "empresa1@example.com",
//     "celular": "+523323341",
//     "rubroId": 1
//   }

// curl -H "Authorization: "  